version: "3.9"
services:
  webapp-placium:
    volumes:
      - /opt2/upload:/upload/

  fias-placium:
    volumes:
      - /opt2/fias/data:/var/lib/postgresql/data

  osm-placium:
    volumes:
      - /opt2/osm/data:/var/lib/postgresql/data

  manticore-placium:
    volumes:
      - /opt2/manticore/run:/var/manticore/run
      - /opt2/manticore/log:/var/manticore/log
      - /opt2/manticore/data:/var/manticore/data
      - /opt2/manticore/manticore.conf:/etc/manticoresearch/manticore.conf

  nginx-placium:
    volumes:
      - /opt2/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt2/nginx/cache:/data/nginx/cache

  pgadmin-placium:
    volumes:
      - /opt2/pgadmin:/var/lib/pgadmin
