version: "3.9"
services:
  webapp-placium:
    volumes:
      - //y/placium/upload:/upload/

  fias-placium:
    volumes:
      - //y/placium/fias/data:/var/lib/postgresql/data

  osm-placium:
    volumes:
      - //y/placium/osm/data:/var/lib/postgresql/data

  manticore-placium:
    volumes:
      - //y/placium/manticore/run:/var/manticore/run
      - //y/placium/manticore/log:/var/manticore/log
      - //y/placium/manticore/data:/var/manticore/data
      - //y/placium/manticore/manticore.conf:/etc/manticoresearch/manticore.conf
 
  nginx-placium:
    volumes:
      - //y/placium/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - //y/placium/nginx/cache:/data/nginx/cache
