version: "3.9"
services:
  webapp-placium:
    volumes:
      - //y/placium/upload:/upload/

  fias-placium:
    volumes:
      - //y/placium/fias/data:/var/lib/postgresql/data

  osm-placium:
    volumes:
      - //y/placium/osm/data:/var/lib/postgresql/data

  sphinx-placium:
    volumes:
      - //y/placium/sphinx/conf:/etc/sphinxsearch:ro
      - //y/placium/sphinx/data:/var/lib/sphinx/data

  nginx-placium:
    volumes:
      - //y/placium/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - //y/placium/nginx/cache:/data/nginx/cache
