version: "3.9"
networks:
  placium:
    name: placium_dev
    driver: bridge 

services:
  webapp-placium:
    container_name: webapp-placium
    build:
      context: .
      dockerfile: Placium.WebApp/Dockerfile
    ports:
      - "9966:9966"
      - "9967:9967"
    depends_on:
      - fias-placium
      - osm-placium
      - sphinx-placium
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__FiasConnection: "Host=fias-placium;Port=5432;Database=fias_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Command Timeout=0"
      ConnectionStrings__OsmConnection: "Host=osm-placium;Port=5432;Database=osm_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Command Timeout=0"
      ConnectionStrings__SphinxConnection: "Host=sphinx-placium;Port=9306;Command Timeout=0"
      UploadConfig__Path: "/upload"
      AccountConfig__Password: "!QAZ2wsx"
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:9966
      Kestrel__Endpoints__Https__Url: http://0.0.0.0:9967
    volumes:
      - ../upload:/upload/
    networks:
      - placium
    logging:
      driver: local 

  webapi-placium:
    container_name: webapi-placium
    build:
      context: .
      dockerfile: Placium.WebApi/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - fias-placium
      - osm-placium
      - sphinx-placium
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__FiasConnection: "Host=fias-placium;Port=5432;Database=fias_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Command Timeout=0"
      ConnectionStrings__OsmConnection: "Host=osm-placium;Port=5432;Database=osm_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Command Timeout=0"
      ConnectionStrings__SphinxConnection: "Host=sphinx-placium;Port=9306;Command Timeout=0"
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5000
      Kestrel__Endpoints__Https__Url: http://0.0.0.0:5001
    networks:
      - placium
    logging:
      driver: local 

  fias-placium:
    image: "postgres"
    container_name: fias-placium
    ports:
      - "15432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: fias_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ../postgres/data:/var/lib/postgresql/data
    networks:
      - placium
    logging:
      driver: none

  osm-placium:
    image: "postgis/postgis"
    container_name: osm-placium
    ports:
      - "25432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: osm_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ../postgis/data:/var/lib/postgresql/data
    networks:
      - placium
    logging:
      driver: none

  sphinx-placium:
    image: "stefobark/sphinxdocker"
    container_name: sphinx-placium
    ports:
      - "19306:9306"
    restart: always
    volumes:
      - ../sphinx/conf:/etc/sphinxsearch
      - ../sphinx/data:/var/lib/sphinx/data
    networks:
      - placium
    logging:
      driver: none

  nginx-placium:
    image: "nginx"
    container_name: nginx-placium
    depends_on:
      - webapi-placium
    ports:
      - "6699:80"
    restart: always
    volumes:
      - ../nginx/conf:/etc/nginx
      - ../nginx/cache:/datanginx/cache
    networks:
      - placium
    logging:
      driver: none
