version: "3.9"
networks:
  placium:
    name: placium_dev
    driver: bridge 

services:
  webapp-placium:
    container_name: webapp-placium
    build:
      context: .
      dockerfile: Placium.WebApp/Dockerfile
    ports:
      - "9966:9966"
      - "9977:9977"
    depends_on:
      - fias-placium
      - osm-placium
      - sphinx-placium
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__FiasConnection: "Host=fias-placium;Port=5432;Database=fias_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Command Timeout=0"
      ConnectionStrings__OsmConnection: "Host=osm-placium;Port=5432;Database=osm_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Command Timeout=0"
      ConnectionStrings__SphinxConnection: "Host=sphinx-placium;Port=9306;Command Timeout=0"
      UploadConfig__Path: "/upload"
      AccountConfig__Password: "${ADMIN_PASSWORD}"
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:9966
      Kestrel__Endpoints__Https__Url: http://0.0.0.0:9977
    networks:
      - placium

  webapi-placium:
    container_name: webapi-placium
    build:
      context: .
      dockerfile: Placium.WebApi/Dockerfile
    depends_on:
      - fias-placium
      - osm-placium
      - sphinx-placium
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__FiasConnection: "Host=fias-placium;Port=5432;Database=fias_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Command Timeout=0"
      ConnectionStrings__OsmConnection: "Host=osm-placium;Port=5432;Database=osm_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Command Timeout=0"
      ConnectionStrings__SphinxConnection: "Host=sphinx-placium;Port=9306;Command Timeout=0"
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5000
      Kestrel__Endpoints__Https__Url: http://0.0.0.0:5001
    networks:
      - placium

  fias-placium:
    image: "postgres"
    container_name: fias-placium
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: fias_db
      PGDATA: /var/lib/postgresql/data
    networks:
      - placium

  osm-placium:
    image: "postgis/postgis"
    container_name: osm-placium
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: osm_db
      PGDATA: /var/lib/postgresql/data
    networks:
      - placium

  sphinx-placium:
    image: "stefobark/sphinxdocker"
    container_name: sphinx-placium
    restart: always
    networks:
      - placium

  nginx-placium:
    image: "nginx"
    container_name: nginx-placium
    depends_on:
      - webapi-placium
    ports:
      - "8080:8080"
    restart: always
    networks:
      - placium
