# copy this file for every deployment profile, aka tag

# Default version of the deployed Visary services
.vis: &default
  tag: 0.3.44

# Global configuration items, used in all deployments
global:
  defaultConfig:
    appsettings.json:
      StartupOptions:
        Seed: true

#------------------
# Visary services
#------------------

visary-api-gateway:
  <<: *default

#==================
